import requests

"""
http request to the user's Canvas url,
where Canvas requires authentication with OAuth2

Parameter:
 - url: string for the Canvas url (ex: canvas.eee.uci.edu)
 - tkn: token from the user, has to be manually generated by them

Output:
returns a response object under the requests library
"""
def API_Call(url, token):
    # Set up query string to send the OAuth2 token

    payload = {"access_token" : token}
    # Concatenate url and query, and get a http request
    # response = requests.get(url, params=payload)
    response = requests.get(url, params=payload)

    # reuturn the response object
    return response


def main():
    # Get user to input their token\
    tkn = input("Please input your token: ")

    # 403 error though if accessing grades (need to replace <course_id>)
    # url = "https://canvas.eee.uci.edu/api/v1/courses/<course_id>/gradebook_history/feed"
    url = "https://canvas.eee.uci.edu/api/v1/users/self/todo"
    # Do API Call
    response = API_Call(url, tkn)

    # check if request has a response, and print out contents if successful response
    print("Status Code: " + str(response.status_code))
    if (response.status_code == 200):
        print("Request Succeeded")
        print(response.json)

        # Get all of contents from the API call
        # print(response.content)
    else:
        print("Request Error")



if __name__ == "__main__":
    main()
